service: zfg-slack-command

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  stage: sandbox
  region: eu-west-2
  deploymentBucket:
      name: sandbox.zfg.element43.xyz

package:
  exclude:
    - '*'
    - .git/**
    - .idea/**
    - src/**
    - test/**
    - '!dist/**'
  excludeDevDependencies: true

functions:
  zfg:
    name: zfg
    description: Type `/zfg` and give zero f*cks...
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
